### ISSUE TITLE
The Heading inside of mega menu in All departments section is not clear.

### ISSUE THREAD

**Issue by kunal22-gupta** [kunal22-gupta/Shopify#1]
If you go into the all departments section and hover over Home & Kitchen. The heading inside of that mega menu is not clear and is getting overshadowed by the linear gradient effect. The lists are whereas unaffected. 

You can check out the website here https://kunal22-gupta.github.io/Shopify/

![image](https://github.com/kunal22-gupta/Shopify/assets/88278364/7b868824-adba-4b86-96b4-8ffddbffe138)

**Comment by J4Web** [comment]
Hey Kunal,

I wanted to try and look into the issue, if you assign me the issue, I could have a look at it?

**Comment by kunal22-gupta** [comment]
> Hey Kunal,
> 
> I wanted to try and look into the issue, if you assign me the issue, I could have a look at it?

Assigned it to you. Do let me know if you need any help.

**Comment by StrixV54** [comment]
@kunal22-gupta Hi, I will work on this and fix this in some time.
